### ISSUE TITLE
Module 'FreeMode' instead of 'freeMode'

### ISSUE THREAD

**Issue by eelke** [sinankeskin/ember-swiper7#319] opened 2023-04-26 13:06 UTC
In the documentation it says `NOTICE: All module names are case-sensitive.`
But loading the module `freeMode` throws an error. `FreeMode` works fine.

**Comment by sinankeskin** [comment] 2023-04-26 13:47
This is really awkward because at that time I checked all modules names one by one and realized freeMode should be camel case all other modules starts with capital letter @eelke 
<img width="1269" alt="image" src="https://user-images.githubusercontent.com/2091777/234594933-6d4408e0-a062-41de-872e-e80feae4589c.png">

<img width="1290" alt="image" src="https://user-images.githubusercontent.com/2091777/234595247-a2436c59-2148-4e63-9ae8-deeef0f3e94d.png">

Checked with that version from npm-package and confirmed. Could you please check which version are you using? You can check with `yarn why swiper`

**Comment by sinankeskin** [comment] 2023-04-26 13:58
Nope you were right. Import is with capital F. Updating docs. Sorry about this.

<img width="651" alt="image" src="https://user-images.githubusercontent.com/2091777/234598919-230399e3-a61e-4f49-9be7-fe46df8b32da.png">

**Comment by eelke** [comment] 2023-04-26 14:00
Yeah it's confusing isn't it! Because their v7 docs also only mention the module with a small f: 
https://v7.swiperjs.com/swiper-api#free-mode

**Comment by sinankeskin** [comment] 2023-04-26 15:20
Definitely terrible authoring :)

**Comment by sinankeskin** [comment] 2023-05-04 18:27
Oh I'm closing this since I've updated the docs. Feel free to reach me if you need anything.

**Closed by sinankeskin** 2023-05-04 18:27 UTC
